# Generated by Django 5.0.3 on 2024-03-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dffhdss', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
